[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
version = "0.0.1"
name = "news-summarizer"

requires-python = ">= 3.12"

dependencies = ["playwright==1.50.0 "]

[tool.poetry]
package-mode=false